spring:
  application:
    name: devpub-app
  mvc:
    locale: ${MVC_LOCALE}
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  mail:
    protocol: ${MAIL_PROTOCOL}
    host: ${MAIL_HOST}
    port: ${MAIL_HOST_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  servlet:
   multipart:
      max-file-size: ${MAX_UPLOAD_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}

mail-sender:
  debug: true
  sender-name: ${MAIL_SENDER_NAME}

#FLYWAY
flyway:
  user: ${JDBC_DATABASE_USERNAME}
  password: ${JDBC_DATABASE_PASSWORD}

#mail page
default:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 254-44-16
  email: oleg071984@gmail.com
  copyright: AllCoders Inc.
  copyrightFrom: 2020

#Cloudinary
cloudinary:
  cloud-name: ${CLY_CLOUD_NAME}
  apikey: ${CLY_APIKEY}
  api-secret: ${CLY_API_SECRET}

#Captcha
captcha:
  image:
    format: png
    width: 100
    height: 35
    compress-ratio: 1.0F
  token:
    min-length: 3
    delta: 2
  storage-limit: 1

announce:
  string:
    length: 48
    end: ...

#Local storage
storage:
  root:
    location: tmp_storage
  image:
    allowed-formats: jpg, png

#Swagger OpenAPI docs
springdoc:
  api-docs:
    path: /api-json
  swagger-ui:
    path: /api-view
