spring:
  mvc:
    locale: ru
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/devpub?stringtype=unspecified}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:123}
  mail:
    protocol: smtps
    host: smtp.gmail.com
    port: 465
    username: dev.pub.adm@gmail.com
    password: smazrpsyukerpgkl

mail-sender:
  debug: true
  sender-name: DevPub

#FLYWAY
flyway:
  user: ${JDBC_DATABASE_USERNAME:postgres}
  password: ${JDBC_DATABASE_PASSWORD:123}

#mail page
default:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005

#Cloudinary
cloudinary:
  cloud-name: hg7rd5cd5
  apikey: 556696283735317
  api-secret: sMG-S3M4UU7v9oi5D5F0YGnkyRI

#Captcha
captcha:
  image:
    format: png
    width: 100
    height: 35
    compress-ratio: 1.0F
  token:
    min-length: 3
    delta: 2
  storage-limit: 1

time-offset: +03:00 #разница во времени с UTC

announce:
  string:
    length: 48
    end: ...

#Local storage
storage:
  max-size: 200000 #в байтах
  root:
    location: tmp_storage
  image:
    allowed-formats: jpg, png

