
create type setting_value as enum ('YES', 'NO');

create table global_settings (
    id int8 generated by default as identity,
    code varchar(255) not null,
    name varchar(255) not null,
    value setting_value not null,
    primary key (id)
);

insert into global_settings(code, name, value)
    values ('MULTIUSER_MODE', 'Многопользовательский режим', 'YES'),
    ('POST_PREMODERATION', 'Премодерация постов', 'YES'),
    ('STATISTICS_IS_PUBLIC', 'Показывать всем статистику блога', 'YES')
