create table captcha_codes (
    id int8 generated by default as identity,
    time timestamp with time zone not null,
    code varchar(255) not null,
    secret_code varchar(255) not null,
    primary key (id)
);

