create table users (
    id int8 generated by default as identity,
    is_moderator boolean not null,
    reg_time timestamp with time zone not null,
    name varchar(255) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    code varchar(255) null,
    photo varchar(255) null,
    primary key (id)
);

