create table users_roles (
    id int8 generated by default as identity,
    user_id int8 not null,
    role_id int8 not null,
    primary key (user_id, role_id),
    constraint fk_users
    foreign key (user_id) references users (id),
    constraint fk_roles
    foreign key (role_id) references roles (id)
);

